### ISSUE TITLE
How Can I Contact You Directly?

### ISSUE THREAD

**Issue by lukebranch** [hoangpq/WebStarter#1]
Hi @hoangpq ,

Please let me know how I can get in touch with you directly via email. I have a few things i'd like to discuss with you.

**Comment by hoangpq** [comment]
Oh, Sr you can ping me directly via skype `hoang.phanquoc`

**Comment by lukebranch** [comment]
@hoangpq ,

Thanks, i'll add you on Skype now and close this issue. Much appreciated.
